// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package appstream

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/hashicorp/packer-plugin-amazon/builder/common"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName                     *string                           `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType                   *string                           `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion                   *string                           `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug                         *bool                             `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce                         *bool                             `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError                       *string                           `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars                      map[string]string                 `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars                 []string                          `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`
	AccessKey                           *string                           `mapstructure:"access_key" required:"true" cty:"access_key" hcl:"access_key"`
	AssumeRole                          *common.FlatAssumeRoleConfig      `mapstructure:"assume_role" required:"false" cty:"assume_role" hcl:"assume_role"`
	CustomEndpointEc2                   *string                           `mapstructure:"custom_endpoint_ec2" required:"false" cty:"custom_endpoint_ec2" hcl:"custom_endpoint_ec2"`
	CredsFilename                       *string                           `mapstructure:"shared_credentials_file" required:"false" cty:"shared_credentials_file" hcl:"shared_credentials_file"`
	DecodeAuthZMessages                 *bool                             `mapstructure:"decode_authorization_messages" required:"false" cty:"decode_authorization_messages" hcl:"decode_authorization_messages"`
	InsecureSkipTLSVerify               *bool                             `mapstructure:"insecure_skip_tls_verify" required:"false" cty:"insecure_skip_tls_verify" hcl:"insecure_skip_tls_verify"`
	MaxRetries                          *int                              `mapstructure:"max_retries" required:"false" cty:"max_retries" hcl:"max_retries"`
	MFACode                             *string                           `mapstructure:"mfa_code" required:"false" cty:"mfa_code" hcl:"mfa_code"`
	ProfileName                         *string                           `mapstructure:"profile" required:"false" cty:"profile" hcl:"profile"`
	RawRegion                           *string                           `mapstructure:"region" required:"true" cty:"region" hcl:"region"`
	SecretKey                           *string                           `mapstructure:"secret_key" required:"true" cty:"secret_key" hcl:"secret_key"`
	SkipMetadataApiCheck                *bool                             `mapstructure:"skip_metadata_api_check" cty:"skip_metadata_api_check" hcl:"skip_metadata_api_check"`
	SkipCredsValidation                 *bool                             `mapstructure:"skip_credential_validation" cty:"skip_credential_validation" hcl:"skip_credential_validation"`
	Token                               *string                           `mapstructure:"token" required:"false" cty:"token" hcl:"token"`
	VaultAWSEngine                      *common.FlatVaultAWSEngineOptions `mapstructure:"vault_aws_engine" required:"false" cty:"vault_aws_engine" hcl:"vault_aws_engine"`
	PollingConfig                       *common.FlatAWSPollingConfig      `mapstructure:"aws_polling" required:"false" cty:"aws_polling" hcl:"aws_polling"`
	DirectoryName                       *string                           `cty:"directory_name" hcl:"directory_name"`
	OrganizationalUnitDistinguishedName *string                           `cty:"organizational_unit_distinguished_name" hcl:"organizational_unit_distinguished_name"`
	SecurityGroupIds                    []string                          `cty:"security_group_ids" hcl:"security_group_ids"`
	SubnetIds                           []string                          `cty:"subnet_ids" hcl:"subnet_ids"`
	VolumeSizeInGb                      *int32                            `cty:"volume_size_in_gb" hcl:"volume_size_in_gb"`
	SkipCreateImage                     *bool                             `mapstructure:"skip_create_image" required:"false" cty:"skip_create_image" hcl:"skip_create_image"`
	Name                                *string                           `mapstructure:"name" required:"true" cty:"name" hcl:"name"`
	Description                         *string                           `mapstructure:"description" required:"false" cty:"description" hcl:"description"`
	DisplayName                         *string                           `mapstructure:"display_name" required:"false" cty:"display_name" hcl:"display_name"`
	EnableDefaultInternetAccess         *bool                             `mapstructure:"enable_default_internet_access" required:"false" cty:"enable_default_internet_access" hcl:"enable_default_internet_access"`
	SourceImageName                     *string                           `mapstructure:"source_image_name" required:"true" cty:"source_image_name" hcl:"source_image_name"`
	InstanceType                        *string                           `mapstructure:"instance_type" required:"true" cty:"instance_type" hcl:"instance_type"`
	IamRoleArn                          *string                           `mapstructure:"iam_role_arn" required:"false" cty:"iam_role_arn" hcl:"iam_role_arn"`
	AppstreamAgentVersion               *string                           `mapstructure:"appstream_agent_version" required:"false" cty:"appstream_agent_version" hcl:"appstream_agent_version"`
	SoftwaresToInstall                  []string                          `mapstructure:"softwares_to_install" required:"false" cty:"softwares_to_install" hcl:"softwares_to_install"`
	SoftwaresToUninstall                []string                          `mapstructure:"softwares_to_uninstall" required:"false" cty:"softwares_to_uninstall" hcl:"softwares_to_uninstall"`
	Tags                                map[string]string                 `mapstructure:"tags" required:"false" cty:"tags" hcl:"tags"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"packer_build_name":                      &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":                    &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":                    &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":                           &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":                           &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":                        &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":                  &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables":             &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"access_key":                             &hcldec.AttrSpec{Name: "access_key", Type: cty.String, Required: false},
		"assume_role":                            &hcldec.BlockSpec{TypeName: "assume_role", Nested: hcldec.ObjectSpec((*common.FlatAssumeRoleConfig)(nil).HCL2Spec())},
		"custom_endpoint_ec2":                    &hcldec.AttrSpec{Name: "custom_endpoint_ec2", Type: cty.String, Required: false},
		"shared_credentials_file":                &hcldec.AttrSpec{Name: "shared_credentials_file", Type: cty.String, Required: false},
		"decode_authorization_messages":          &hcldec.AttrSpec{Name: "decode_authorization_messages", Type: cty.Bool, Required: false},
		"insecure_skip_tls_verify":               &hcldec.AttrSpec{Name: "insecure_skip_tls_verify", Type: cty.Bool, Required: false},
		"max_retries":                            &hcldec.AttrSpec{Name: "max_retries", Type: cty.Number, Required: false},
		"mfa_code":                               &hcldec.AttrSpec{Name: "mfa_code", Type: cty.String, Required: false},
		"profile":                                &hcldec.AttrSpec{Name: "profile", Type: cty.String, Required: false},
		"region":                                 &hcldec.AttrSpec{Name: "region", Type: cty.String, Required: false},
		"secret_key":                             &hcldec.AttrSpec{Name: "secret_key", Type: cty.String, Required: false},
		"skip_metadata_api_check":                &hcldec.AttrSpec{Name: "skip_metadata_api_check", Type: cty.Bool, Required: false},
		"skip_credential_validation":             &hcldec.AttrSpec{Name: "skip_credential_validation", Type: cty.Bool, Required: false},
		"token":                                  &hcldec.AttrSpec{Name: "token", Type: cty.String, Required: false},
		"vault_aws_engine":                       &hcldec.BlockSpec{TypeName: "vault_aws_engine", Nested: hcldec.ObjectSpec((*common.FlatVaultAWSEngineOptions)(nil).HCL2Spec())},
		"aws_polling":                            &hcldec.BlockSpec{TypeName: "aws_polling", Nested: hcldec.ObjectSpec((*common.FlatAWSPollingConfig)(nil).HCL2Spec())},
		"directory_name":                         &hcldec.AttrSpec{Name: "directory_name", Type: cty.String, Required: false},
		"organizational_unit_distinguished_name": &hcldec.AttrSpec{Name: "organizational_unit_distinguished_name", Type: cty.String, Required: false},
		"security_group_ids":                     &hcldec.AttrSpec{Name: "security_group_ids", Type: cty.List(cty.String), Required: false},
		"subnet_ids":                             &hcldec.AttrSpec{Name: "subnet_ids", Type: cty.List(cty.String), Required: false},
		"volume_size_in_gb":                      &hcldec.AttrSpec{Name: "volume_size_in_gb", Type: cty.Number, Required: false},
		"skip_create_image":                      &hcldec.AttrSpec{Name: "skip_create_image", Type: cty.Bool, Required: false},
		"name":                                   &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"description":                            &hcldec.AttrSpec{Name: "description", Type: cty.String, Required: false},
		"display_name":                           &hcldec.AttrSpec{Name: "display_name", Type: cty.String, Required: false},
		"enable_default_internet_access":         &hcldec.AttrSpec{Name: "enable_default_internet_access", Type: cty.Bool, Required: false},
		"source_image_name":                      &hcldec.AttrSpec{Name: "source_image_name", Type: cty.String, Required: false},
		"instance_type":                          &hcldec.AttrSpec{Name: "instance_type", Type: cty.String, Required: false},
		"iam_role_arn":                           &hcldec.AttrSpec{Name: "iam_role_arn", Type: cty.String, Required: false},
		"appstream_agent_version":                &hcldec.AttrSpec{Name: "appstream_agent_version", Type: cty.String, Required: false},
		"softwares_to_install":                   &hcldec.AttrSpec{Name: "softwares_to_install", Type: cty.List(cty.String), Required: false},
		"softwares_to_uninstall":                 &hcldec.AttrSpec{Name: "softwares_to_uninstall", Type: cty.List(cty.String), Required: false},
		"tags":                                   &hcldec.AttrSpec{Name: "tags", Type: cty.Map(cty.String), Required: false},
	}
	return s
}
